In [46]:
import pandas as pd
import numpy as np

mainData = pd.read_csv('Data/US-pumpkins.csv')

In [47]:
columns_selected = ['City Name', 'Package', 'Variety', 'Origin', 'Item Size','Color']
mainData = mainData[columns_selected]
mainData.dropna(inplace=True)
mainData.head(50)

     City Name               Package  ... Item Size   Color
2    BALTIMORE          24 inch bins  ...       med  ORANGE
3    BALTIMORE          24 inch bins  ...       med  ORANGE
4    BALTIMORE          24 inch bins  ...       lge  ORANGE
5    BALTIMORE          24 inch bins  ...       lge  ORANGE
6    BALTIMORE          36 inch bins  ...       med  ORANGE
7    BALTIMORE          36 inch bins  ...       lge  ORANGE
8    BALTIMORE          36 inch bins  ...       med  ORANGE
9    BALTIMORE          36 inch bins  ...       lge  ORANGE
10   BALTIMORE          36 inch bins  ...       med  ORANGE
11   BALTIMORE          36 inch bins  ...       lge  ORANGE
12   BALTIMORE          36 inch bins  ...       lge  ORANGE
13   BALTIMORE          36 inch bins  ...       med  ORANGE
14   BALTIMORE          36 inch bins  ...       lge  ORANGE
15   BALTIMORE          36 inch bins  ...       med  ORANGE
16   BALTIMORE          36 inch bins  ...       lge  ORANGE
17   BALTIMORE          36 inch bins  ...       med  ORANGE
18   BALTIMORE          36 inch bins  ...       sml  ORANGE
19   BALTIMORE          36 inch bins  ...      xlge  ORANGE
20   BALTIMORE          36 inch bins  ...       lge  ORANGE
21   BALTIMORE          36 inch bins  ...       med  ORANGE
22   BALTIMORE          36 inch bins  ...       lge  ORANGE
23   BALTIMORE          36 inch bins  ...   med-lge  ORANGE
24   BALTIMORE          36 inch bins  ...   med-lge  ORANGE
25   BALTIMORE          36 inch bins  ...       lge  ORANGE
26   BALTIMORE          36 inch bins  ...   med-lge  ORANGE
70   BALTIMORE  1 1/9 bushel cartons  ...       med  ORANGE
71   BALTIMORE  1 1/9 bushel cartons  ...       sml  ORANGE
72   BALTIMORE  1 1/9 bushel cartons  ...       sml  ORANGE
73   BALTIMORE  1 1/9 bushel cartons  ...       med  ORANGE
75   BALTIMORE  1 1/9 bushel cartons  ...       sml  ORANGE
76   BALTIMORE  1 1/9 bushel cartons  ...       med  ORANGE
79   BALTIMORE  1 1/9 bushel cartons  ...       med  ORANGE
82   BALTIMORE  1 1/9 bushel cartons  ...       med  ORANGE
85   BALTIMORE  1 1/9 bushel cartons  ...       med  ORANGE
87   BALTIMORE  1 1/9 bushel cartons  ...       med  ORANGE
88   BALTIMORE  1 1/9 bushel cartons  ...       med  ORANGE
89   BALTIMORE  1 1/9 bushel cartons  ...       med  ORANGE
90   BALTIMORE  1 1/9 bushel cartons  ...       med  ORANGE
91   BALTIMORE  1 1/9 bushel cartons  ...       med  ORANGE
92   BALTIMORE  1 1/9 bushel cartons  ...       med  ORANGE
93   BALTIMORE          24 inch bins  ...       sml  ORANGE
94   BALTIMORE          24 inch bins  ...       sml  ORANGE
95   BALTIMORE          24 inch bins  ...       sml  ORANGE
104  BALTIMORE          24 inch bins  ...       jbo   WHITE
105  BALTIMORE          24 inch bins  ...       lge   WHITE
106  BALTIMORE          24 inch bins  ...       med   WHITE
108  BALTIMORE          24 inch bins  ...       jbo   WHITE
109  BALTIMORE          24 inch bins  ...       jbo   WHITE
110  BALTIMORE          24 inch bins  ...       lge   WHITE
111  BALTIMORE          24 inch bins  ...       med   WHITE

[50 rows x 6 columns]

In [48]:
from sklearn.preprocessing import OrdinalEncoder, OneHotEncoder, LabelEncoder
from sklearn.compose import ColumnTransformer

#Ordinal Encoding
item_size_categories = [['sml', 'med', 'med-lge', 'lge', 'xlge', 'jbo', 'exjbo']]
ordinal_feature = ['Item Size']
ordinal_encoder =  OrdinalEncoder(categories=item_size_categories)

#OneHot Encoding
onehot_feature = ['City Name', 'Package', 'Variety', 'Origin']
onehot_encoder = OneHotEncoder(sparse_output=False)

#Compose columns

ct = ColumnTransformer(transformers=[
    ('ord', ordinal_encoder, ordinal_feature),
    ('cat', onehot_encoder, onehot_feature)
])
ct.set_output(transform='pandas')
feature_encoded = ct.fit_transform(mainData)

#Label Encoding
label_encoder = LabelEncoder()
label_encoded = label_encoder.fit_transform(mainData['Color'])

#Merging
newData = feature_encoded.assign(Target_color=label_encoded)
newData.head(50)

     ord__Item Size  cat__City Name_ATLANTA  ...  cat__Origin_VIRGINIA  Target_color
2               1.0                     0.0  ...                   0.0             0
3               1.0                     0.0  ...                   1.0             0
4               3.0                     0.0  ...                   0.0             0
5               3.0                     0.0  ...                   0.0             0
6               1.0                     0.0  ...                   0.0             0
7               3.0                     0.0  ...                   0.0             0
8               1.0                     0.0  ...                   0.0             0
9               3.0                     0.0  ...                   0.0             0
10              1.0                     0.0  ...                   0.0             0
11              3.0                     0.0  ...                   0.0             0
12              3.0                     0.0  ...                   0.0             0
13              1.0                     0.0  ...                   0.0             0
14              3.0                     0.0  ...                   0.0             0
15              1.0                     0.0  ...                   0.0             0
16              3.0                     0.0  ...                   0.0             0
17              1.0                     0.0  ...                   0.0             0
18              0.0                     0.0  ...                   0.0             0
19              4.0                     0.0  ...                   0.0             0
20              3.0                     0.0  ...                   0.0             0
21              1.0                     0.0  ...                   0.0             0
22              3.0                     0.0  ...                   0.0             0
23              2.0                     0.0  ...                   0.0             0
24              2.0                     0.0  ...                   0.0             0
25              3.0                     0.0  ...                   0.0             0
26              2.0                     0.0  ...                   0.0             0
70              1.0                     0.0  ...                   0.0             0
71              0.0                     0.0  ...                   0.0             0
72              0.0                     0.0  ...                   0.0             0
73              1.0                     0.0  ...                   0.0             0
75              0.0                     0.0  ...                   0.0             0
76              1.0                     0.0  ...                   0.0             0
79              1.0                     0.0  ...                   0.0             0
82              1.0                     0.0  ...                   0.0             0
85              1.0                     0.0  ...                   0.0             0
87              1.0                     0.0  ...                   0.0             0
88              1.0                     0.0  ...                   0.0             0
89              1.0                     0.0  ...                   0.0             0
90              1.0                     0.0  ...                   0.0             0
91              1.0                     0.0  ...                   0.0             0
92              1.0                     0.0  ...                   0.0             0
93              0.0                     0.0  ...                   1.0             0
94              0.0                     0.0  ...                   0.0             0
95              0.0                     0.0  ...                   0.0             0
104             5.0                     0.0  ...                   0.0             1
105             3.0                     0.0  ...                   0.0             1
106             1.0                     0.0  ...                   0.0             1
108             5.0                     0.0  ...                   1.0             1
109             5.0                     0.0  ...                   0.0             1
110             3.0                     0.0  ...                   0.0             1
111             1.0                     0.0  ...                   0.0             1

[50 rows x 49 columns]

In [49]:
from sklearn import model_selection, linear_model
from sklearn.metrics import f1_score, classification_report, confusion_matrix

X = newData[newData.columns.difference(['Target_color'])]
y = newData['Target_color']

X_train, X_test, y_train, y_test = model_selection.train_test_split(X, y, test_size=0.2, random_state=0)
model = linear_model.LogisticRegression()
model.fit(X_train, y_train)
y_hat = model.predict(X_test)

print(classification_report(y_test, y_hat))
print(f"f1-score: {f1_score(y_test, y_hat):.3f} \n")
print(confusion_matrix(y_test, y_hat))

              precision    recall  f1-score   support

           0       0.94      0.98      0.96       166
           1       0.85      0.67      0.75        33

    accuracy                           0.92       199
   macro avg       0.89      0.82      0.85       199
weighted avg       0.92      0.92      0.92       199

f1-score: 0.746

[[162   4]
 [ 11  22]]